config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }
  get "welcome/index"  
  root to: "welcome#index"  
  resources :campings
  resources :villes
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/camping.rb
class Camping < ApplicationRecord
	belongs_to :ville
end

app/controllers/campings_controller.rb
class CampingsController < ApplicationController
  before_action :set_camping, only: %i[ show edit update destroy ]

  # GET /campings or /campings.json
  def index
    @campings = Camping.all
  end

  # GET /campings/1 or /campings/1.json
  def show
  end

  # GET /campings/new
  def new
    @camping = Camping.new
  end

  # GET /campings/1/edit
  def edit
  end

  # POST /campings or /campings.json
  def create
    @camping = Camping.new(camping_params)

    respond_to do |format|
      if @camping.save
        format.html { redirect_to @camping, notice: "Camping was successfully created." }
        format.json { render :show, status: :created, location: @camping }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @camping.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /campings/1 or /campings/1.json
  def update
    respond_to do |format|
      if @camping.update(camping_params)
        format.html { redirect_to @camping, notice: "Camping was successfully updated." }
        format.json { render :show, status: :ok, location: @camping }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @camping.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /campings/1 or /campings/1.json
  def destroy
    @camping.destroy
    respond_to do |format|
      format.html { redirect_to campings_url, notice: "Camping was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_camping
      @camping = Camping.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def camping_params
      params.require(:camping).permit(:name, :body, :ville_id)
    end
end

app/helpers/campings_helper.rb
module CampingsHelper
end

app/views/campings/_form.html.erb
<%= form_with(model: camping, local: true) do |form| %>
  <% if camping.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(camping.errors.count, "error") %> prohibited this camping from being saved:</h2>

      <ul>
        <% camping.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="field">
    <%= form.label :ville_id %>
    <%= form.number_field :ville_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/campings/edit.html.erb
<h1>Editing Camping</h1>

<%= render 'form', camping: @camping %>

<%= link_to 'Show', @camping %> |
<%= link_to 'Back', campings_path %>

app/views/campings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Campings</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Body</th>
      <th>Ville</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @campings.each do |camping| %>
      <tr>
        <td><%= camping.name %></td>
        <td><%= camping.body %></td>
        <td><%= camping.ville_id %></td>
        <td><%= link_to 'Show', camping %></td>
        <td><%= link_to 'Edit', edit_camping_path(camping) %></td>
        <td><%= link_to 'Destroy', camping, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Camping', new_camping_path %>

app/views/campings/new.html.erb
<h1>New Camping</h1>

<%= render 'form', camping: @camping %>

<%= link_to 'Back', campings_path %>

app/views/campings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @camping.name %>
</p>

<p>
  <strong>Body:</strong>
  <%= @camping.body %>
</p>

<p>
  <strong>Ville:</strong>
  <%= @camping.ville_id %>
</p>

<%= link_to 'Edit', edit_camping_path(@camping) %> |
<%= link_to 'Back', campings_path %>