config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }
  get "welcome/index"  
  root to: "welcome#index"  
  resources :campings
  resources :villes
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/ville.rb
class Ville < ApplicationRecord
	has_many :campings
end

app/controllers/villes_controller.rb
class VillesController < ApplicationController
  before_action :set_ville, only: %i[ show edit update destroy ]

  skip_before_action :authenticate_user!, :only => [:index]

  # GET /villes or /villes.json
  def index
    @villes = Ville.all
  end

  # GET /villes/1 or /villes/1.json
  def show
    @campings = @ville.campings.all
    @camping = @ville.campings.build
  end

  # GET /villes/new
  def new
    @ville = Ville.new
  end

  # GET /villes/1/edit
  def edit
  end

  # POST /villes or /villes.json
  def create
    @ville = Ville.new(ville_params)

    respond_to do |format|
      if @ville.save
        format.html { redirect_to @ville, notice: "Ville was successfully created." }
        format.json { render :show, status: :created, location: @ville }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @ville.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /villes/1 or /villes/1.json
  def update
    respond_to do |format|
      if @ville.update(ville_params)
        format.html { redirect_to @ville, notice: "Ville was successfully updated." }
        format.json { render :show, status: :ok, location: @ville }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @ville.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /villes/1 or /villes/1.json
  def destroy
    @ville.destroy
    respond_to do |format|
      format.html { redirect_to villes_url, notice: "Ville was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ville
      @ville = Ville.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def ville_params
      params.require(:ville).permit(:name, :description, :picture)
    end
end

app/helpers/villes_helper.rb
module VillesHelper
end

app/views/villes/_form.html.erb
<%= form_with(model: ville, local: true) do |form| %>
  <% if ville.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ville.errors.count, "error") %> prohibited this ville from being saved:</h2>

      <ul>
        <% ville.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :picture %>
    <%= form.text_field :picture %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/villes/edit.html.erb
<h1>Editing Ville</h1>

<%= render 'form', ville: @ville %>

<%= link_to 'Show', @ville %> |
<%= link_to 'Back', villes_path %>

app/views/villes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Villes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Picture</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @villes.each do |ville| %>
      <tr>
        <td><%= ville.name %></td>
        <td><%= ville.description %></td>
        <td><%= ville.picture %></td>
        <td><%= link_to 'Show', ville %></td>
        <td><%= link_to 'Edit', edit_ville_path(ville) %></td>
        <td><%= link_to 'Destroy', ville, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ville', new_ville_path %>

app/views/villes/new.html.erb
<h1>New Ville</h1>

<%= render 'form', ville: @ville %>

<%= link_to 'Back', villes_path %>

app/views/villes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @ville.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @ville.description %>
</p>

<p>
  <strong>Picture:</strong>
  <%= @ville.picture %>
</p>

<%= link_to 'Edit', edit_ville_path(@ville) %> |
<%= link_to 'Back', villes_path %>